sudo: required
dist: trusty
addons:
  apt:
    packages:
    - wget
language: ruby
rvm:
- 2.1.5
env:
- PACKAGE_TARGET=deb
install: bundle install
script:
- "./build.sh"
deploy:
  - provider: bintray
    file: ".bintray/deb.json"
    user: patdowney
    key:
      secure: OFDy1c1gqbhEkzK0gJEHzCcFkBHQwbVXvvZSyS7+bGQzK9W2vQ3h79RafcYYRvytjjaMNoB6/x/0XVRNhdHNVrCgutNcM+PEqk3FvKCsAMDQGekeqImFkyBRlKGzOZYp7zZnsefu/HBz+6TqMoT4CFshoOIim0lDgBidvHBWuTeNbGAnyLRZR3QTPBAIGdR5YUAFI0IGg01NqliuoAVQMcOTPpbr8TazzZ2i9JkoqJdnaDXlX90CAY2ig9yt5kyajovn1kuVn6CM/xUaZxeKLqFfXtkBcZNMcG2a8Zy5aMGZufZHNrAQtiDwCVzdlgpCLiJATdjlGMcO+eTOC9ySH1Notp/N8+29oSQMa+hoN/HuQCsYaF7OIcONOOUlZpd/SPQmJRwcQ8CzBb+rTI9s0ccfoGI58DxhR1d3uNBANDe8jirOJ0S8zf97k6vDa2WKX6bauLf3SAMUMJWZTF2NSgPcVf2H+LRVTSBR6bDqyAlGAwMIbu6xRmfwSSxY3XfzHQW6SDunQm7ENpv2/H80MhwoVfVe7/sPU0XfyaVMgIdXrqBR3k5ovpBiZiXndC9p8DlxaldJPI+4ROFCkzjlrx27rUtqLEJn2VwkYEPkPwsb16X5zbHf/DjgpWN4esME4fQ5En1nFivdQ8lfzQx5FQwfl/KoDKu9KpMB6c/NqVk=
    on:
      condition: "$PACKAGE_TARGET = deb"
