sudo: required
dist: trusty
addons:
  apt:
    packages:
    - wget
    - rpm
language: ruby
rvm:
- 2.1.5
install: bundle install
script:
- "make"
deploy:
  - provider: bintray
    file: ".bintray/deb.json"
    user: patdowney
    key:
      secure: "Aa5NPKoh0ruLjQlzlxFvv+ke2PTjgmc1fke87G97QkdEX1k2IqP/YzxxM8RYYM6exQSgV2itLO2sGGRf3MHfuPb/bvHuLQ+4QPxeglZ7KtMVBr0aI1XD8Ho7vfbDd49r3hP6Kd+htyXjLpzw46AWzmyNxXDWwSsdd3ZG/d2Or0dTcTCrPhRLmVSrlc0Z5JxIKB1E1w6WhMk8+fhg+na5r1md3cIYuHGlaINv9o0ZWDmYUHhCuUsTX1RTJ+W0ehy3vEmEn8xhphtO3MPfzkoBnnabNUmuDe0qlrR21ECIGc1ePQz2AvSlLNGNv4uPQTD4aCWVsV9Bdi8ikJqo/xEK3dFnNttdDJYky/lM+vuEYYwe/+V1T8DecmTeh2rjGLmco24/AqS85cjOFHvHBnBGX9DelsL7Wq37cPxZJ2ElyykHoo7Lk2iympFs5ggZSIa2zsXxl1SA6uHspmx6y/bt5AVw+7e5yNBB+Etkw4UKH4v/rXMgQwi9Ri7TMA1nD0SGNCUwoP9zT32vt1+VUYwTJ5uVfgkceDMD+jQZQFCeCXb1qkXbXluYLUhpgFG+9hFOY0QY5GN9kZDe8+tQP/VKOLY7U2yiBwY4zjHgen8zZ2JgAG59NWd+gjWEv2PIaf2ofdGamZhel0JtMWJ4PrXGJhXuISxBkPJ4y5Dfahc7Z58="
  - provider: bintray
    file: ".bintray/rpm.json"
    user: patdowney
    key:
      secure: "Aa5NPKoh0ruLjQlzlxFvv+ke2PTjgmc1fke87G97QkdEX1k2IqP/YzxxM8RYYM6exQSgV2itLO2sGGRf3MHfuPb/bvHuLQ+4QPxeglZ7KtMVBr0aI1XD8Ho7vfbDd49r3hP6Kd+htyXjLpzw46AWzmyNxXDWwSsdd3ZG/d2Or0dTcTCrPhRLmVSrlc0Z5JxIKB1E1w6WhMk8+fhg+na5r1md3cIYuHGlaINv9o0ZWDmYUHhCuUsTX1RTJ+W0ehy3vEmEn8xhphtO3MPfzkoBnnabNUmuDe0qlrR21ECIGc1ePQz2AvSlLNGNv4uPQTD4aCWVsV9Bdi8ikJqo/xEK3dFnNttdDJYky/lM+vuEYYwe/+V1T8DecmTeh2rjGLmco24/AqS85cjOFHvHBnBGX9DelsL7Wq37cPxZJ2ElyykHoo7Lk2iympFs5ggZSIa2zsXxl1SA6uHspmx6y/bt5AVw+7e5yNBB+Etkw4UKH4v/rXMgQwi9Ri7TMA1nD0SGNCUwoP9zT32vt1+VUYwTJ5uVfgkceDMD+jQZQFCeCXb1qkXbXluYLUhpgFG+9hFOY0QY5GN9kZDe8+tQP/VKOLY7U2yiBwY4zjHgen8zZ2JgAG59NWd+gjWEv2PIaf2ofdGamZhel0JtMWJ4PrXGJhXuISxBkPJ4y5Dfahc7Z58="
